# Generated by Django 5.2.5 on 2025-08-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='area_size',
            field=models.PositiveIntegerField(blank=True, help_text='Area size in square meters', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(blank=True, choices=[('ready', 'Ready to Move'), ('under_construction', 'Under Construction')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bhk',
            field=models.CharField(blank=True, choices=[('1bhk', '1 BHK'), ('2bhk', '2 BHK'), ('3bhk', '3 BHK'), ('4bhk', '4 BHK')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('rental', 'Rental'), ('property', 'Property for Sale')], default='property', help_text='Is this a rental property or property for sale?', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='furnishing',
            field=models.CharField(blank=True, choices=[('furnished', 'Furnished'), ('semi', 'Semi-Furnished'), ('unfurnished', 'Unfurnished')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='property_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='images_urls',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs as JSON array', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
