# Generated by Django 5.2.5 on 2025-08-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_category_size_remove_product_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste an external image/video URL', null=True),
        ),
    ]
